- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes

  vars:
   mysql_db_user: owncloud_dbadmin
   mysql_db_password: ownclouddb
   php_timezone: Asia/Tokyo
   path_document_root: /var/www/html/owncloud

  tasks:
  - name: OS timezone to JST
   # OSのタイムゾーンをJSTに変更。
    shell: cp -p  /usr/share/zoneinfo/Japan /etc/localtime

  - name: Install ownCloud reopsitory
  #CentOS6.x用ownCloudレポジトリのインストール。
    get_url: url=http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-6/isv:ownCloud:community.repo dest=/etc/yum.repos.d/

  - name: Install EPEL and Remi repository
  # EPEL/Remiのレポジトリをインストールする
    yum: name={{ item }}
    with_items:
      - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm    
  
  - name: yum repo enabled=0
  # 明示的に指定したいのでenabledは全て0にする
    replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
    with_items:
      - epel.repo
      - remi.repo

  - name: Uninstall OLD MySQL packages
  # 古いMySQLをアンインストール。
    yum: name=mysql-* state=absent
    
  - name: Install Apache packages
  # Apache をインストール。
    yum: name=httpd state=present

  - name: Install mod_ssl
  # mod_ssl をインストール。
    yum: name=mod_ssl state=present

  - name: Install libraries and packages
  # CentOSのライブラリとパッケージをインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - libzip
      - libzip-devel
      - zlib-devel
      - libaio
      - pcre
      - pcre-devel
      - gcc
      - setools-libs
      - audit-libs-python
      - freetype
      - libXpm
      - libcgroup
      - libselinux-python
      - libsemanage-python

  - name: Install PHP5.4
  # PHP5.4をインストール。
    yum: name="{{ item }}" state=present enablerepo=remi
    with_items:
      - php
      - php-cli
      - php-devel
      - php-mysqlnd
      - php-gd
      - php-pdo

  - name: Install MySQL5.5
  # MySQL5.5をインストール。
    yum: pkg={{ item }} state=present enablerepo=remi,epel
    with_items:
      - mysql
      - mysql-server
      - mysql-devel
      - MySQL-python

  - name: restart mysqld 
  # MySQLの起動
    service: name=mysqld state=started

  - name: ownCloud DB Setting
  # ownCloudのデータベース設定を実施する。
    mysql_db: name=owncloud
    mysql_user: name={{ mysql_db_user }} password={{ mysql_db_password }} priv=owncloud.*:ALL

  - name: Install ownCloud
  # ownCloudのインストール。
    yum: name=owncloud state=present enablerepo=isv_ownCloud_community,remi

  - name: Make owncloud data dir
  # ownCloud用データ領域の作成
    file: dest=/owncloud/data owner=apache group=apache state=directory

  - name: Change php timezone
  # phpタイムゾーンの変更
    replace: >-
      dest=/etc/php.ini
      regexp="^;date\.timezone ="
      replace="date.timezone = {{ php_timezone }}"

  - name: Change php setting 
  # PHPの設定変更
  # change expose_php
    replace: >-
       dest=/etc/php.ini
       regexp="^expose_php = On"
       replace="expose_php = Off"

    # Change php default_charset
    replace: >-
       dest=/etc/php.ini
       regexp=";default_charset ="
       replace="default_charset ="

  - name: Change Apache DocumentRoot
  # Apache DocumentRootの変更。
    replace: >-
       dest='/etc/httpd/conf/httpd.conf'
       regexp='^DocumentRoot .*'
       replace='DocumentRoot "{{ path_document_root }}/"'

  - name: restart httpd 
  # Apacheの再起動
    service: name=httpd state=restarted enabled=yes

  - name: restart mysqld 
  # MySQLの再起動
    service: name=mysqld state=restarted
